openapi: 3.0.1
info:
  title: '@jupiterone/graph-mongodb'
  description: An integration and graph conversion project for MongoDB
  x-cortex-git:
    github:
      repository: JupiterOne/graph-mongodb
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-mongodb'
